# .bashrc

# User specific aliases and functions
export PATH=$PATH:~/scripts;
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias vi='vim'
alias ll='ls -l'

## color variables
green="\[\e[1;32m\]"
red="\[\e[1;31m\]"
yellow="\[\e[1;33m\]"
normal="\[\e[0m\]"

##PS1 output
PS1="[$red\u@$green\h$yellow$normal][\W]\\\$ "

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
