apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: printalive
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec: 
          containers:
          - name: printalive-container
            image: busybox
            args:
              - /bin/sh
              - -c
              - date; echo the pod is alive!
          restartPolicy: OnFailure
