apiVersion: v1
kind: PersistentVolume
metadata:  
  name: 10gb-nfs-pv-01
spec:  
  capacity:    
    storage: 20Gi  
  volumeMode: Filesystem  
  accessModes:    
    - ReadWriteOnce      ### 访问模式: 单人读写
  persistentVolumeReclaimPolicy: Recycle  
  storageClassName: nfs  
  mountOptions:    
    - hard    
  nfs:    
    path: /nfs/webFiles
    server: 192.168.6.198
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 10gb-nfs-pv-02
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce      ### 访问模式: 单人读写
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
  nfs:
    path: /nfs/webFiles
    server: 192.168.6.198
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 10gb-nfs-pv-03
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce      ### 访问模式: 单人读写
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
  nfs:
    path: /nfs/webFiles
    server: 192.168.6.198
